blog_transcoder_aws/transcoder/audio_transcoder/urls.py
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views

urlpatterns = [
    url(
        regex=r'^upload/$',
        view=views.UploadAudioFileView.as_view(),
        name='upload'
    ),
    url(
        regex=r'^(?P<pk>\d+)/$',
        view=views.AudioFileDetailView.as_view(),
        name='detail'
    ),
    url(
        regex=r'^transcode-complete/$',
        view=views.transcode_complete,
        name='transcode-complete'
    )
]

blog_transcoder_aws/transcoder/config/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import TemplateView

urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name='home.html'), name='home'),
    url(r'^admin/', admin.site.urls),
    url(r'^audio/', include('audio_transcoder.urls', namespace='audio')),
    url(
        r'^messages/',
        include(
            'transcode_messages.urls',
            namespace='messages'
        )
    ),
]

blog_transcoder_aws/transcoder/transcode_messages/urls.py
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views


urlpatterns = [
    url(
        regex=r'^read/$',
        view=views.read_message,
        name='read-message'
    )
]

blog_transcoder_aws/transcoder/audio_transcoder/models.py
import uuid

from django.db import models


def unique_file_path(instance, filename):
    new_file_name = uuid.uuid4()
    return '{}'.format(str(new_file_name))


class AudioFile(models.Model):
    name = models.CharField(max_length=100, blank=True)
    mp3_file = models.FileField(upload_to=unique_file_path)
    flac_file = models.FileField(blank=True, upload_to=unique_file_path)
    wav_file = models.FileField(blank=True, upload_to=unique_file_path)
    mp4_file = models.FileField(blank=True, upload_to=unique_file_path)
    was_processed = models.BooleanField(default=False)

    def __str__(self):
        return self.name

blog_transcoder_aws/transcoder/transcode_messages/models.py
from django.db import models


class Message(models.Model):
    text = models.CharField(max_length=250)
    read = models.BooleanField(default=False)

    def __str__(self):
        return self.text

blog_transcoder_aws/transcoder/audio_transcoder/forms.py
from django.forms import ModelForm

from .models import AudioFile


class AudioFileFrom(ModelForm):

    class Meta:
        model = AudioFile
        fields = ['name', 'mp3_file']

blog_transcoder_aws/transcoder/audio_transcoder/views.py
import json

from django.conf import settings
from django.contrib import messages
from django.core.urlresolvers import reverse
from django.http import (HttpResponse, HttpResponseForbidden,
                         HttpResponseNotAllowed, HttpResponseRedirect)
from django.views.decorators.csrf import csrf_exempt
from django.views.generic.detail import DetailView, View
from django.views.generic.edit import FormView

from aws_transcoder.transcoder import transcoder
from transcode_messages.models import Message

from .forms import AudioFileFrom
from .models import AudioFile
from .utlis import convert_sns_str_to_json


class UploadAudioFileView(FormView):
    template_name = 'upload.html'
    form_class = AudioFileFrom

    def form_valid(self, form):
        audio_file = AudioFile(
            name=self.get_form_kwargs().get('data')['name'],
            mp3_file=self.get_form_kwargs().get('files')['mp3_file']
        )
        audio_file.save()
        wav_filename, flac_filename, mp4_filename = transcoder.start_transcode(
            filename=audio_file.mp3_file.name
        )
        audio_file.mp4_file = mp4_filename
        audio_file.flac_file = flac_filename
        audio_file.wav_file = wav_filename
        audio_file.save()
        return HttpResponseRedirect(
            reverse('audio:detail', kwargs={'pk': audio_file.pk})
        )

    def get_success_url(self):
        return reverse('home')


class AudioFileDetailView(DetailView):
    template_name = 'audiofile_detail.html'
    model = AudioFile


@csrf_exempt
def transcode_complete(request):
    if request.method != 'POST':
        return HttpResponseNotAllowed(request.method)
    if request.META['HTTP_X_AMZ_SNS_TOPIC_ARN'] != settings.SNS_TOPIC_ARN:
        return HttpResponseForbidden('Not vaild SNS topic ARN')
    json_body = json.loads(request.body.decode('utf-8'), object_hook=convert_sns_str_to_json)
    if json_body['Message']['state'] == 'COMPLETED':
        audio_file = AudioFile.objects.get(
            mp3_file=json_body['Message']['input']['key'][6:]
        )
        Message.objects.create(
            text='Your file {} has been processed'.format(audio_file.name)
        )
    return HttpResponse('OK')

blog_transcoder_aws/transcoder/transcode_messages/views.py
from .models import Message
from django.http import HttpResponse


def read_message(request):
    message = Message.objects.get(id=request.POST['message_id'])
    message.readed = True
    message.save()
    return HttpResponse('OK')

blog_transcoder_aws/transcoder/templates/audiofile_detail.html
{% extends 'base.html' %}

{% block content %}
<h1>{{ object.name }}<h1>
<ul><a href="{{ object.mp3_file.url }}">Mp3 File</a></ul>
{% if object.flac_file %}
    <ul><a href="{{ object.flac_file.url}}">Flac File</a></ul>
{% endif %}
{% if object.wav_file.url %}
    <ul><a href="{{ object.wav_file.url}}">Wav File</a></ul>
{% endif %}
{% if object.mp4_file.url %}
    <ul><a href="{{ object.mp4_file.url}}">Mp4 File</a><ul>
{% endif %}
{% endblock content %}

blog_transcoder_aws/transcoder/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" ng-app>
{% load bootstrap3 %}
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %}Transcoder{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    {% block css %}
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">


    <!-- Your stuff: Third-party css libraries go here -->

    <!-- This file store project specific CSS -->
    <link href="{% static 'css/project.css' %}" rel="stylesheet">
    {% endblock %}

  </head>

  <body>

    <nav class="navbar navbar-inverse">
        <div class="container">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">Transcoder</a>
          </div>
          <div class="navbar-collapse collapse" aria-expanded="false" style="height: 1px;">
            <ul class="nav navbar-nav">
              <li class="active"><a href="{% url 'home' %}">Home</a></li>
              <li><a href="{% url 'audio:upload' %}">Upload File</a></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </nav>

      <div class="container">

        {% if messages %}
      	  {% for message in messages %}
            <div class="alert alert-success alert-dismissible" data-message-id="{{ message.id }}" data-message-url="{% url 'messages:read-message' %}"role="alert">
              <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">x</span>
              </button>
              {{ message.text }}
            </div>
      	  {% endfor %}
        {% endif %}

        {% block content %}
        {% endblock content %}

      </div> <!-- /container -->

      {% block modal %}{% endblock modal %}

      <!-- Le javascript
      ================================================== -->
      <!-- Placed at the end of the document so the pages load faster -->
      {% block javascript %}
      <script src="https://code.jquery.com/jquery-3.1.1.min.js" integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8=" crossorigin="anonymous"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
      <script src="{% static 'js/js.cookie.js' %}"></script>
      <!-- place project specific Javascript in this file -->
      <script src="{% static 'js/project.js' %}"></script>
      {% endblock javascript %}
    </body>
 </html>

blog_transcoder_aws/transcoder/templates/home.html
{% extends 'base.html' %}
{% block content %}
<div class="well">
    <h2>Main page of transcoder project.</h2>
</div>
{% endblock content %}

blog_transcoder_aws/transcoder/templates/upload.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="form-group">
        {{ form.as_p }}
    </div>
    <input type="submit" value="Submit" class="btn btn-primary" >
</form>
</div>
{% endblock content %}
Status API Training Shop Blog About